routes:
  api_simple_action:
    path: /api/{section}
    controller: ApiPlatform\Controller\IApiRouter::route

  api_action:
    path: /api/{section}/{action}
    controller: ApiPlatform\Controller\IApiRouter::route

  api_action_entity:
    path: /api/{section}/{action}/{identifier}
    controller: ApiPlatform\Controller\IApiRouter::route