services:
  ApiPlatform\IApi:
    class: ApiPlatform\Api

  ApiPlatform\Controller\IApiRouter:
    class: ApiPlatform\Controller\ApiRouter

  ApiPlatform\Controller\ExceptionControllerDecorator:
    decorates: Runway\Controller\IExceptionController

  ApiPlatform\Controller\System\IApiResponseController:
    class: ApiPlatform\Controller\System\ApiResponseController

  ApiPlatform\Controller\System\IApiExceptionResponseController:
    class: ApiPlatform\Controller\System\ApiExceptionResponseController

  ApiPlatform\Provider\Endpoints\IEndpointsProvider:
    class: ApiPlatform\Provider\Endpoints\EndpointsProvider

  ApiPlatform\Provider\EndpointMethodParameters\IEndpointMethodParametersProvider:
    class: ApiPlatform\Provider\EndpointMethodParameters\EndpointMethodParametersProvider

  ApiPlatform\Validator\IEndpointMethodParameterValidator:
    class: ApiPlatform\Validator\EndpointMethodParameterValidator

  ApiPlatform\Provider\EndpointMethodParameterValue\IEndpointMethodParameterValidator:
    class: ApiPlatform\Provider\EndpointMethodParameterValue\EndpointMethodParameterValidator

  ApiPlatform\Provider\EndpointMethodParameterValue\IEndpointMethodParameterValueProvider:
    class: ApiPlatform\Provider\EndpointMethodParameterValue\EndpointMethodParameterValueProvider

  ApiPlatform\Storage\ITokenStorage:
    class: ApiPlatform\Storage\TokenStorage
    arguments:
      tokenHeader: '#API_TOKEN_HEADER'

  ApiPlatform\V1\IApi:
    class: ApiPlatform\Api

  ApiPlatform\Core\ICrypto:
    class: ApiPlatform\Core\Crypto
    arguments:
      cipher: 'AES-256-CBC'
      options: 1
      hashAlgo: 'sha256'
      sha2Length: 32

  ApiPlatform\Singleton\IAuth:
    class: ApiPlatform\Singleton\Auth
    arguments:
      key: '#API_CRYPTO_KEY'
      keyLength: '#API_CRYPTO_KEY_LENGTH'

  response.json.successful:
    class: Runway\Request\Response
    arguments:
      code: 200,
      headers:
        Content-Type: application/json